# Generated by Django 5.0.6 on 2024-05-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_product_qty_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='fname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='lname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(max_length=50),
        ),
    ]
